name: Update Profile JSON

on:
  workflow_dispatch:  # يتيح تشغيل الأكشن يدويًا

jobs:
  update-profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update profile.json
        run: |
          echo '{
            "profilePicture": "https://your-image-url.com",
            "coverPicture": "https://your-cover-url.com",
            "bio": "هذا هو البايو الجديد!"
          }' > profile.json

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add profile.json
          git commit -m "تحديث تلقائي لملف profile.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
